###
GET {{host}}/api/health/

> {%
client.test("Test request status code", function (){
     client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
 %}

>>! dev/http_response/check_health.json

###

POST {{host}}/api/clipboard/

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
client.global.set("clipboard_id", response.body["id"]);
 %}

>>! dev/http_response/create_clipboard.json

###
PATCH {{host}}/api/clipboard/{{clipboard_id}}/
Content-Type: application/x-www-form-urlencoded

nickName=asdfg

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
 %}

>>! dev/http_response/patch_clipboard.json

###
GET {{host}}/api/clipboard/{{clipboard_id}}/

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
    client.assert(response.body["nickName"]==="asdfg", "Nickname not correct")
});
client.global.set("clipboard_id", response.body["id"]);
 %}

>>! dev/http_response/fetch_clipboard.json


###
GET {{host}}/api/clipboard/45c3da67-0000-0000-0000-b720db10694d/

> {%
client.test("Test request status code", function (){
    client.assert(response.status===404, `Response status is not 404, but ${response.status}`)
});
 %}

>>! dev/http_response/fetch_clipboard_not_found.json


###

PUT {{host}}/api/clipboard/{{clipboard_id}}/item/
Content-Type: application/x-www-form-urlencoded

content=aaaaa

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
client.global.set("clipitem_id", response.body["id"]);
client.global.set("clipitem_preview", response.body["preview"]);
 %}

>>! dev/http_response/create_clipitem.json

###

GET {{host}}/api/clipboard/{{clipboard_id}}/item/{{clipitem_id}}

> {%
client.test("Test response correctness", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`);
    const previewFromResponse=response.body["preview"];
    const previewFromEnv=client.global.get("clipitem_preview");
    client.assert(previewFromResponse==="aaaaa", `Response preview not correct, ${previewFromResponse}!=${previewFromEnv}`);
});
 %}

>>! dev/http_response/fetch_clipitem.json

###

GET {{host}}/api/clipboard/{{clipboard_id}}/item/{{clipitem_id}}/content

> {%
client.test("Test response correctness", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`);
    client.assert(response.body==="aaaaa", `Response content not correct`);
});
 %}

>>! dev/http_response/fetch_clipitem_content.json

###

PUT {{host}}/api/clipboard/{{clipboard_id}}/item/
Content-Type: application/x-www-form-urlencoded

content=bbbbbdhadkjhalskdhlaksjhd

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
 %}

>>! dev/http_response/create_clipitem_2.json

###

GET {{host}}/api/clipboard/{{clipboard_id}}/item/

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
 %}

>>! dev/http_response/fetch_all_clipitems.json

###

DELETE {{host}}/api/clipboard/{{clipboard_id}}/item/{{clipitem_id}}

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
 %}

>>! dev/http_response/delete_clipitem.json

###

DELETE {{host}}/api/clipboard/{{clipboard_id}}/

> {%
client.test("Test request status code", function (){
    client.assert(response.status >= 200 && response.status < 300, `Response status is not 2xx but ${response.status}`)
});
 %}

>>! dev/http_response/delete_clipboard.json